"""003_add_cert

Revision ID: a7e3a661421b
Revises: d17cb85cd541
Create Date: 2025-12-29 12:38:50.552895

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e3a661421b'
down_revision: Union[str, Sequence[str], None] = 'd17cb85cd541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('employee', sa.String(length=128), nullable=False),
    sa.Column('check_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED', name='status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('used_at', sa.Date(), nullable=True),
    sa.Column('indefinite', sa.Boolean(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.execute("""
        CREATE SEQUENCE IF NOT EXISTS certificates_code_seq START WITH 1 INCREMENT BY 1;
    """)

    op.execute("""
               CREATE
               OR REPLACE FUNCTION certificates_set_code()
        RETURNS trigger AS $$
        DECLARE
               seq_val bigint;
               BEGIN
            IF
               NEW.code IS NULL OR NEW.code = '' THEN
                seq_val := nextval('certificates_code_seq');
                NEW.code
               := 'AN-' || lpad(seq_val::text, 6, '0');
               END IF;

               RETURN NEW;
               END;
        $$
               LANGUAGE plpgsql;
               """)

    op.execute("""
               CREATE TRIGGER trg_certificates_set_code
                   BEFORE INSERT
                   ON certificates
                   FOR EACH ROW
                   EXECUTE FUNCTION certificates_set_code();
               """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_certificates_set_code ON certificates;")
    op.execute("DROP FUNCTION IF EXISTS certificates_set_code();")
    op.execute("DROP SEQUENCE IF EXISTS certificates_code_seq;")
    op.drop_table('certificates')
