FROM node:22-slim as build

WORKDIR /frontend

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    openssl

COPY frontend/package.json frontend/package-lock.json /frontend/
COPY frontend/.npmrc /frontend/.npmrc
RUN npm install

COPY frontend/src /frontend/src
COPY frontend/public /frontend/public
COPY frontend/nginx.conf /frontend/nginx.conf
COPY frontend/vite.config.* /frontend/
COPY frontend/index.html /frontend/index.html

RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /frontend/dist /usr/share/nginx/html
COPY --from=build /frontend/nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod -R a+rX /usr/share/nginx/html
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
